spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  websocket:
    message-broker:
      enabled: true
server:
  port: 8085
